msrv = "1.85.0"
cognitive-complexity-threshold = 30
too-many-lines-threshold = 100
too-many-arguments-threshold = 7
type-complexity-threshold = 250
large-error-threshold = 256
allow-expect-in-tests = true
allow-unwrap-in-tests = true
allow-dbg-in-tests = true
allow-print-in-tests = true
allow-panic-in-tests = true
allow-indexing-slicing-in-tests = true
avoid-breaking-exported-api = false
future-size-threshold = 4096
