// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextConfig } from "./ContextConfig";
import type { ViewportConfig } from "./ViewportConfig";

export type BrowserConfig = {
  browser: string;
  backend: string;
  channel?: string;
  headless: boolean;
  executablePath?: string;
  args: Array<string>;
  viewport?: ViewportConfig;
  slowMo?: number;
  /**
   * Playwright `use` block: per-project context defaults.
   */
  use: ContextConfig;
};
