// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeolocationConfig } from "./GeolocationConfig";
import type { HttpCredentialsConfig } from "./HttpCredentialsConfig";
import type { ProxyConfig } from "./ProxyConfig";

export type ContextConfig = {
  isMobile: boolean;
  hasTouch: boolean;
  colorScheme?: string;
  locale?: string;
  deviceScaleFactor?: number;
  offline: boolean;
  javaScriptEnabled: boolean;
  bypassCsp: boolean;
  acceptDownloads: boolean;
  userAgent?: string;
  timezoneId?: string;
  geolocation?: GeolocationConfig;
  permissions: Array<string>;
  extraHttpHeaders: { [key in string]: string };
  httpCredentials?: HttpCredentialsConfig;
  ignoreHttpsErrors: boolean;
  proxy?: ProxyConfig;
  serviceWorkers?: string;
  storageState?: string;
  reducedMotion?: string;
  forcedColors?: string;
};
