// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpConfig } from "./McpConfig";
import type { TestConfig } from "./TestConfig";

/**
 * Top-level configuration document.
 */
export type FerridriverConfig = {
  /**
   * MCP server configuration.
   */
  mcp: McpConfig;
  /**
   * Test runner configuration.
   */
  test: TestConfig;
};
