// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HttpCredentialsConfig = {
  username: string;
  password: string;
  origin?: string;
};
