// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpInstanceConfig } from "./McpInstanceConfig";
import type { McpViewportDef } from "./McpViewportDef";

/**
 * Browser launch and per-instance configuration.
 */
export type McpBrowserConfig = {
  /**
   * Browser backend: "cdp-pipe" (default), "cdp-raw", "bidi".
   */
  backend?: string;
  /**
   * Run browsers in headless mode.
   */
  headless?: boolean;
  /**
   * Path to Chrome/Chromium executable.
   */
  executablePath?: string;
  /**
   * Default viewport dimensions for new pages.
   */
  viewport?: McpViewportDef;
  /**
   * Base Chrome arguments applied to ALL browser instances.
   */
  chromeArgs: Array<string>;
  /**
   * External command to get per-instance Chrome args.
   * `${INSTANCE}` is replaced with the instance name.
   * Output: one arg per line, or JSON array of strings.
   */
  instanceArgsCommand?: string;
  /**
   * External command to discover a running browser instance.
   * `${INSTANCE}` is replaced with the instance name.
   * Output: a `ws://` URL on the first line, or empty for "not found".
   */
  instanceDiscoverCommand?: string;
  /**
   * Cache TTL in seconds for command outputs (default: 300).
   */
  commandCacheTtl?: number;
  /**
   * Static per-instance overrides (keyed by instance name).
   */
  instances: { [key in string]: McpInstanceConfig };
  /**
   * Default config for instances not listed in `instances`.
   */
  defaultInstance?: McpInstanceConfig;
};
