// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpBrowserConfig } from "./McpBrowserConfig";
import type { McpServerConfig } from "./McpServerConfig";

/**
 * Root MCP-section configuration loaded from a unified `ferridriver.{toml,yaml,json}`
 * file under the `[mcp]` table.
 */
export type McpConfig = {
  /**
   * MCP server metadata.
   */
  server: McpServerConfig;
  /**
   * Browser launch and instance configuration.
   */
  browser: McpBrowserConfig;
};
