// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-instance configuration.
 */
export type McpInstanceConfig = {
  /**
   * Additional Chrome arguments for this instance.
   */
  chromeArgs: Array<string>;
  /**
   * Explicit WebSocket URL to connect to (skip launch).
   */
  connectUrl?: string;
  /**
   * Path to Chrome profile directory for `DevToolsActivePort` discovery.
   * `${INSTANCE}` is replaced with the instance name. Supports `~` expansion.
   */
  discoverProfile?: string;
};
