// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * MCP server metadata configuration.
 */
export type McpServerConfig = {
  /**
   * Server name for MCP `get_info` (default: "ferridriver").
   */
  name?: string;
  /**
   * Full override of server instructions. If set, replaces the default instructions entirely.
   */
  instructions?: string;
  /**
   * Additional instructions appended to the default ferridriver instructions.
   * Ignored if `instructions` is set.
   */
  extraInstructions?: string;
};
