// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserConfig } from "./BrowserConfig";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Project configuration -- matches Playwright's `TestProject`.
 */
export type ProjectConfig = {
  name: string;
  testMatch?: Array<string>;
  testIgnore?: Array<string>;
  testDir?: string;
  browser?: BrowserConfig;
  outputDir?: string;
  snapshotDir?: string;
  retries?: number;
  timeout?: number;
  repeatEach?: number;
  fullyParallel?: boolean;
  grep?: string;
  grepInvert?: string;
  dependencies: Array<string>;
  teardown?: string;
  metadata: JsonValue;
  tag?: Array<string>;
};
