// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration for slow test reporting. Playwright: `reportSlowTests`.
 */
export type ReportSlowTestsConfig = { max: number; threshold: number };
