// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserConfig } from "./BrowserConfig";
import type { ProjectConfig } from "./ProjectConfig";
import type { ReportSlowTestsConfig } from "./ReportSlowTestsConfig";
import type { ReporterConfig } from "./ReporterConfig";
import type { TraceMode } from "./TraceMode";
import type { UpdateSnapshotsMode } from "./UpdateSnapshotsMode";
import type { VideoConfig } from "./VideoConfig";
import type { WebServerConfig } from "./WebServerConfig";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Test runner configuration.
 */
export type TestConfig = {
  testMatch: Array<string>;
  testDir?: string;
  testIgnore: Array<string>;
  timeout: number;
  expectTimeout: number;
  workers: number;
  retries: number;
  reporter: Array<ReporterConfig>;
  outputDir: string;
  browser: BrowserConfig;
  baseUrl?: string;
  projects: Array<ProjectConfig>;
  globalSetup: Array<string>;
  globalTeardown: Array<string>;
  repeatEach: number;
  forbidOnly: boolean;
  fullyParallel: boolean;
  features: Array<string>;
  tags?: string;
  dryRun: boolean;
  failFast: boolean;
  screenshotOnFailure: boolean;
  video: VideoConfig;
  trace: TraceMode;
  storageState?: string;
  webServer: Array<WebServerConfig>;
  maxFailures: number;
  globalTimeout: number;
  ignoreSnapshots: boolean;
  passWithNoTests: boolean;
  tsconfig?: string;
  name?: string;
  failOnFlakyTests: boolean;
  captureGitInfo: boolean;
  snapshotDir?: string;
  snapshotPathTemplate?: string;
  updateSnapshots: UpdateSnapshotsMode;
  preserveOutput: string;
  reportSlowTests?: ReportSlowTestsConfig;
  quiet: boolean;
  configGrep?: string;
  configGrepInvert?: string;
  metadata: JsonValue;
  strict: boolean;
  order: string;
  language?: string;
  profiles: { [key in string]: JsonValue };
  hasBdd: boolean;
};
