// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Trace recording mode. Mirrors Playwright's `trace`.
 */
export type TraceMode = "off" | "on" | "retain-on-failure" | "on-first-retry";
