// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Snapshot update mode. Playwright: `updateSnapshots`.
 */
export type UpdateSnapshotsMode = "all" | "changed" | "missing" | "none";
