// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoMode } from "./VideoMode";

/**
 * Video recording configuration.
 */
export type VideoConfig = { mode: VideoMode; width: number; height: number };
