// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Video recording mode.
 */
export type VideoMode = "off" | "on" | "retain-on-failure";
