// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GracefulShutdown } from "./GracefulShutdown";

/**
 * Web server configuration -- matches Playwright's `webServer` option.
 */
export type WebServerConfig = {
  command?: string;
  staticDir?: string;
  url?: string;
  port: number;
  reuseExistingServer: boolean;
  timeout: number;
  cwd?: string;
  env: { [key in string]: string };
  spa: boolean;
  stdout?: string;
  stderr?: string;
  ignoreHttpsErrors: boolean;
  name?: string;
  gracefulShutdown?: GracefulShutdown;
};
