//! Shared JavaScript shims injected by both `WebKit` hosts.
//!
//! Single source of truth in `crates/ferridriver-webkit-wire/shared_js/*.js`.
//! Both hosts consume the SAME bytes:
//!
//! - **macOS** (`crates/ferridriver/src/backend/webkit/host.m`) — via
//!   `<OUT_DIR>/ferridriver_shared_js.h`, generated by
//!   `crates/ferridriver/build.rs::generate_shared_js_header` from the
//!   `.js` files in this crate.
//! - **Linux** (`crates/ferridriver-webkit-host`) — via the `&'static str`
//!   constants below, which use [`include_str!`] against the same files.
//!
//! Editing a `.js` file changes both hosts in the same build (macOS via
//! the regenerated header, Linux via cargo rebuilding the wire crate).
//! There is no parity drift surface — exactly one place to edit JS.

/// `console.log/warn/error/info/debug/trace` capture. Forwards to the
/// host's `fdConsole` script-message handler. Injected at
/// document-start by both hosts in `Op::CreateView`.
pub const CONSOLE: &str = include_str!("../shared_js/console.js");

/// Uncaught JS error + unhandled rejection capture. Routes a synthesised
/// `{name, message, stack}` through the same `fdConsole` IPC frame with
/// the distinguishing `level: 'pageerror'` marker.
pub const ERROR: &str = include_str!("../shared_js/error.js");

/// `window.alert/confirm/prompt` shim. Posts `{type, message, action}`
/// to `fdDialog` and returns sensible defaults so the page-side
/// continues without blocking.
pub const DIALOG: &str = include_str!("../shared_js/dialog.js");

/// `fetch` + `XMLHttpRequest` interceptor that forwards observations to
/// `fdNetwork` and round-trips route decisions through `fdRoute`.
pub const NETWORK: &str = include_str!("../shared_js/network.js");

/// DOM-walking accessibility-tree builder used when the native AX tree
/// is empty (data: URLs, early documents). Returns a JSON string with
/// the same shape as the native walker.
pub const AX_TREE: &str = include_str!("../shared_js/ax_tree.js");

/// Body passed to `WKWebView.callAsyncJavaScript` /
/// `WebView.call_async_javascript_function`. `__fd_expr` is a named
/// argument bound by the host.
pub const EVAL_BODY: &str = include_str!("../shared_js/eval_body.js");

/// Body for `Op::ReleaseRef` — drops `window.__wr.<ref_id>`.
pub const RELEASE_REF: &str = include_str!("../shared_js/release_ref.js");

/// All shims as `(name, source)` pairs. Used by
/// `crates/ferridriver/build.rs` to emit the Obj-C header and by the
/// integration test asserting both hosts see identical bytes.
pub const ALL: &[(&str, &str)] = &[
  ("CONSOLE", CONSOLE),
  ("ERROR", ERROR),
  ("DIALOG", DIALOG),
  ("NETWORK", NETWORK),
  ("AX_TREE", AX_TREE),
  ("EVAL_BODY", EVAL_BODY),
  ("RELEASE_REF", RELEASE_REF),
];
