// The package's type entry.
//
// `index.d.ts` is generated by napi-rs and describes exactly what its
// macros emitted. `devices` is a module-level VALUE built when the addon
// loads (see `src/devices.rs`), which napi-rs has no way to derive a
// declaration for, so it is declared here alongside a re-export of the
// generated surface.

export * from './index';

/**
 * One entry of Playwright's device registry.
 *
 * `screen` is absent from Playwright's own `DeviceDescriptor` type but
 * present in its data, and a `{ ...devices[name] }` spread carries it.
 */
export interface DeviceDescriptor {
  userAgent: string;
  viewport: { width: number; height: number };
  screen?: { width: number; height: number };
  deviceScaleFactor: number;
  isMobile: boolean;
  hasTouch: boolean;
  defaultBrowserType: 'chromium' | 'firefox' | 'webkit';
}

/**
 * Playwright's device registry, vendored at a pinned version:
 * `browser.newContext({ ...devices['iPhone 15'] })`.
 */
export declare const devices: Record<string, DeviceDescriptor>;
