//! The core-js polyfills `LegacyJavaScript` looks for.
//!
//! Generated from devtools-frontend
//! `front_end/third_party/legacy-javascript/lib/legacy-javascript.js`
//! (`polyfillModuleData`, core-js entries only). Each entry is the
//! JavaScript feature being polyfilled and the core-js module that
//! provides it; the regex that finds either is built by
//! [`super::legacy_javascript::polyfill_expression`].
//!
//! Regenerate rather than hand-edit: upstream adds features as browsers
//! gain them, and a stale table quietly under-reports.

/// `(feature, core-js module)`, 86 entries.
pub const CORE_JS_POLYFILLS: [(&str, &str); 86] = [
  ("Array.prototype.at", "es.array.at"),
  ("Array.prototype.concat", "es.array.concat"),
  ("Array.prototype.copyWithin", "es.array.copy-within"),
  ("Array.prototype.every", "es.array.every"),
  ("Array.prototype.fill", "es.array.fill"),
  ("Array.prototype.filter", "es.array.filter"),
  ("Array.prototype.find", "es.array.find"),
  ("Array.prototype.findIndex", "es.array.find-index"),
  ("Array.prototype.findLast", "es.array.find-last"),
  ("Array.prototype.findLastIndex", "es.array.find-last-index"),
  ("Array.prototype.flat", "es.array.flat"),
  ("Array.prototype.flatMap", "es.array.flat-map"),
  ("Array.prototype.forEach", "es.array.for-each"),
  ("Array.from", "es.array.from"),
  ("Array.prototype.includes", "es.array.includes"),
  ("Array.prototype.indexOf", "es.array.index-of"),
  ("Array.isArray", "es.array.is-array"),
  ("Array.prototype.join", "es.array.join"),
  ("Array.prototype.map", "es.array.map"),
  ("Array.of", "es.array.of"),
  ("Array.prototype.slice", "es.array.slice"),
  ("Array.prototype.some", "es.array.some"),
  ("Array.prototype.sort", "es.array.sort"),
  ("Array.prototype.unshift", "es.array.unshift"),
  ("Math.acosh", "es.math.acosh"),
  ("Math.asinh", "es.math.asinh"),
  ("Math.atanh", "es.math.atanh"),
  ("Math.cbrt", "es.math.cbrt"),
  ("Math.clz32", "es.math.clz32"),
  ("Math.cosh", "es.math.cosh"),
  ("Math.expm1", "es.math.expm1"),
  ("Math.fround", "es.math.fround"),
  ("Math.hypot", "es.math.hypot"),
  ("Math.imul", "es.math.imul"),
  ("Math.log10", "es.math.log10"),
  ("Math.log1p", "es.math.log1p"),
  ("Math.log2", "es.math.log2"),
  ("Math.sign", "es.math.sign"),
  ("Math.sinh", "es.math.sinh"),
  ("Math.tanh", "es.math.tanh"),
  ("Math.trunc", "es.math.trunc"),
  ("Object.assign", "es.object.assign"),
  ("Object.create", "es.object.create"),
  ("Object.entries", "es.object.entries"),
  ("Object.freeze", "es.object.freeze"),
  ("Object.fromEntries", "es.object.from-entries"),
  (
    "Object.getOwnPropertyDescriptor",
    "es.object.get-own-property-descriptor",
  ),
  (
    "Object.getOwnPropertyDescriptors",
    "es.object.get-own-property-descriptors",
  ),
  ("Object.getPrototypeOf", "es.object.get-prototype-of"),
  ("Object.hasOwn", "es.object.has-own"),
  ("Object.is", "es.object.is"),
  ("Object.isExtensible", "es.object.is-extensible"),
  ("Object.isFrozen", "es.object.is-frozen"),
  ("Object.isSealed", "es.object.is-sealed"),
  ("Object.keys", "es.object.keys"),
  ("Object.preventExtensions", "es.object.prevent-extensions"),
  ("Object.seal", "es.object.seal"),
  ("Object.setPrototypeOf", "es.object.set-prototype-of"),
  ("Object.values", "es.object.values"),
  ("Promise.any", "es.promise.any"),
  ("Reflect.apply", "es.reflect.apply"),
  ("Reflect.construct", "es.reflect.construct"),
  ("Reflect.deleteProperty", "es.reflect.delete-property"),
  ("Reflect.get", "es.reflect.get"),
  (
    "Reflect.getOwnPropertyDescriptor",
    "es.reflect.get-own-property-descriptor",
  ),
  ("Reflect.getPrototypeOf", "es.reflect.get-prototype-of"),
  ("Reflect.has", "es.reflect.has"),
  ("Reflect.isExtensible", "es.reflect.is-extensible"),
  ("Reflect.ownKeys", "es.reflect.own-keys"),
  ("Reflect.preventExtensions", "es.reflect.prevent-extensions"),
  ("Reflect.setPrototypeOf", "es.reflect.set-prototype-of"),
  ("String.prototype.codePointAt", "es.string.code-point-at"),
  ("String.prototype.endsWith", "es.string.ends-with"),
  ("String.fromCodePoint", "es.string.from-code-point"),
  ("String.prototype.includes", "es.string.includes"),
  ("String.prototype.matchAll", "es.string.match-all"),
  ("String.raw", "es.string.raw"),
  ("String.prototype.repeat", "es.string.repeat"),
  ("String.prototype.replaceAll", "es.string.replace-all"),
  ("String.prototype.startsWith", "es.string.starts-with"),
  ("String.prototype.substr", "es.string.substr"),
  ("String.prototype.trim", "es.string.trim"),
  ("String.prototype.trimEnd", "es.string.trim-end"),
  ("String.prototype.trimStart", "es.string.trim-start"),
  ("String.prototype.link", "es.string.link"),
  ("Promise.allSettled", "esnext.promise.all-settled"),
];
