use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

/// `(name, filename)` — kept in sync with
/// `crates/ferridriver-webkit-wire/src/js.rs::ALL`. Drift between the
/// two is caught at link time: if the macOS host references
/// `FD_JS_<NAME>` that this header doesn't emit, the linker fails.
const JS_FILES: &[(&str, &str)] = &[
  ("CONSOLE", "console.js"),
  ("ERROR", "error.js"),
  ("DIALOG", "dialog.js"),
  ("NETWORK", "network.js"),
  ("AX_TREE", "ax_tree.js"),
  ("EVAL_BODY", "eval_body.js"),
  ("RELEASE_REF", "release_ref.js"),
];

fn main() {
  let out_dir = std::env::var("OUT_DIR").unwrap_or_else(|e| panic!("OUT_DIR not set by cargo: {e}"));
  let manifest_dir =
    std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|e| panic!("CARGO_MANIFEST_DIR not set by cargo: {e}"));
  let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();

  // The wire crate's `shared_js/` lives one directory up from this
  // crate's manifest. Resolve relative to CARGO_MANIFEST_DIR so we work
  // both in-tree and from a published-crate sysroot layout.
  let shared_js_dir = Path::new(&manifest_dir)
    .join("..")
    .join("ferridriver-webkit-wire")
    .join("shared_js");

  // The Obj-C header is only consumed by the macOS host's `host.m`, so
  // we only emit it there. Linux gets the same bytes via
  // `ferridriver_webkit_wire::js::*` directly (which uses `include_str!`).
  if target_os == "macos" {
    generate_shared_js_header(&shared_js_dir, Path::new(&out_dir));
    build_macos_host(&manifest_dir, &out_dir);
  }

  println!("cargo:rerun-if-changed=build.rs");
  println!("cargo:rerun-if-changed=src/macos/host.m");
  for (_, filename) in JS_FILES {
    println!("cargo:rerun-if-changed={}", shared_js_dir.join(filename).display());
  }
}

/// Compile `src/macos/host.m` into a static library and link it into
/// the Rust binary along with the `Cocoa`, `WebKit`, and `CoreFoundation`
/// frameworks. The Rust `main` function defers to the
/// `fd_webkit_host_main` symbol declared in `host.m`.
fn build_macos_host(manifest_dir: &str, out_dir: &str) {
  let host_m = Path::new(manifest_dir).join("src/macos/host.m");

  cc::Build::new()
    .file(&host_m)
    .flag("-fobjc-arc")
    .flag("-fmodules")
    .include(out_dir) // `#include "ferridriver_shared_js.h"`
    .compile("ferridriver_webkit_host_macos");

  // Frameworks the Obj-C host links against.
  for framework in ["Cocoa", "WebKit", "CoreFoundation"] {
    println!("cargo:rustc-link-arg=-framework");
    println!("cargo:rustc-link-arg={framework}");
  }

  // Tell the consuming crates how to find the binary for runtime
  // discovery — same key the host-crate runtime reads.
  let bin_path = PathBuf::from(out_dir)
    .parent()
    .and_then(|p| p.parent())
    .and_then(|p| p.parent())
    .map(|p| p.join("ferridriver-webkit-host"));
  if let Some(p) = bin_path {
    println!("cargo:host_binary={}", p.display());
  }
}

/// Emit `<OUT_DIR>/ferridriver_shared_js.h`. Each entry in
/// [`JS_FILES`] becomes a `static NSString *const FD_JS_<NAME> = @"..."`
/// literal that `host.m` consumes via `#include`.
fn generate_shared_js_header(shared_js_dir: &Path, out_dir: &Path) {
  let header_path = out_dir.join("ferridriver_shared_js.h");
  let mut out = String::with_capacity(64 * 1024);
  out.push_str("// AUTO-GENERATED — do not edit. Regenerated by build.rs from\n");
  out.push_str("// crates/ferridriver-webkit-wire/shared_js/*.js\n");
  out.push_str("#ifndef FERRIDRIVER_SHARED_JS_H\n#define FERRIDRIVER_SHARED_JS_H\n\n");
  out.push_str("#import <Foundation/Foundation.h>\n\n");

  for (name, filename) in JS_FILES {
    let path = shared_js_dir.join(filename);
    let src = fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    writeln!(
      out,
      "static NSString *const FD_JS_{name} = @\"{}\";",
      escape_for_objc(&src)
    )
    .unwrap_or_else(|e| panic!("write shared_js header buffer: {e}"));
  }

  out.push_str("\n#endif\n");
  fs::write(&header_path, out).unwrap_or_else(|e| panic!("write {}: {e}", header_path.display()));
}

/// Escape `s` for embedding inside an Obj-C `@"..."` literal. Handles
/// every character that would otherwise terminate the string or be
/// interpreted as a C escape: `\\`, `"`, `\n` / `\r` / `\t`, and other
/// control bytes (rendered as `\xNN`). UTF-8 multi-byte sequences pass
/// through unchanged — Obj-C string literals support UTF-8 source.
fn escape_for_objc(s: &str) -> String {
  let mut out = String::with_capacity(s.len() + s.len() / 8);
  for ch in s.chars() {
    match ch {
      '\\' => out.push_str("\\\\"),
      '"' => out.push_str("\\\""),
      '\n' => out.push_str("\\n"),
      '\r' => out.push_str("\\r"),
      '\t' => out.push_str("\\t"),
      c if (c as u32) < 0x20 => {
        write!(out, "\\x{:02x}", c as u32).unwrap_or_else(|e| panic!("escape buf write: {e}"));
      },
      c => out.push(c),
    }
  }
  out
}
