//! WASM component testing: compile Rust components to WASM and test in browser.
//!
//! Supports: Leptos, Dioxus, Yew, Sycamore (any Rust→WASM framework).
//!
//! Flow:
//! 1. `WasmBuilder::build()` compiles a crate to WASM + runs wasm-bindgen
//! 2. `ComponentServer::start()` serves the output directory
//! 3. Browser navigates to the HTML wrapper
//! 4. Waits for `[data-mounted]` attribute (set after WASM init)
//! 5. Test interacts with the mounted component via Page API

use std::path::{Path, PathBuf};
use std::process::Stdio;

/// Which Rust WASM framework the component uses.
#[derive(Debug, Clone, Copy)]
pub enum RustFramework {
  /// Leptos — `leptos::mount_to_body()`
  Leptos,
  /// Dioxus — `dioxus::launch()`
  Dioxus,
  /// Yew — `yew::Renderer::<App>::new().render()`
  Yew,
  /// Sycamore — `sycamore::render()`
  Sycamore,
  /// Generic — user provides their own mount code
  Generic,
}

/// Builds a Rust crate to WASM for component testing.
pub struct WasmBuilder {
  /// Path to the crate containing the component (has Cargo.toml).
  crate_dir: PathBuf,
  /// Output directory for WASM artifacts.
  out_dir: PathBuf,
  /// The binary or lib target name to build.
  target_name: Option<String>,
  /// Release or debug build.
  release: bool,
}

impl WasmBuilder {
  pub fn new(crate_dir: impl Into<PathBuf>, out_dir: impl Into<PathBuf>) -> Self {
    Self {
      crate_dir: crate_dir.into(),
      out_dir: out_dir.into(),
      target_name: None,
      release: false,
    }
  }

  /// Set the target name (binary or lib). If not set, uses the crate's default.
  #[must_use]
  pub fn target(mut self, name: impl Into<String>) -> Self {
    self.target_name = Some(name.into());
    self
  }

  /// Build in release mode.
  #[must_use]
  pub fn release(mut self) -> Self {
    self.release = true;
    self
  }

  /// Compile the crate to WASM and run wasm-bindgen.
  ///
  /// Returns the output directory containing the JS/WASM files.
  ///
  /// # Errors
  ///
  /// Returns an error if cargo build or wasm-bindgen fails.
  pub async fn build(&self) -> Result<PathBuf, String> {
    // Step 1: cargo build --target wasm32-unknown-unknown
    let mut cmd = tokio::process::Command::new("cargo");
    cmd.arg("build");
    cmd.arg("--target").arg("wasm32-unknown-unknown");
    if self.release {
      cmd.arg("--release");
    }
    if let Some(ref name) = self.target_name {
      cmd.arg("--bin").arg(name);
    }
    cmd.current_dir(&self.crate_dir);
    cmd.stdout(Stdio::piped()).stderr(Stdio::piped());

    let output = cmd.output().await.map_err(|e| format!("cargo build: {e}"))?;
    if !output.status.success() {
      let stderr = String::from_utf8_lossy(&output.stderr);
      return Err(format!("cargo build failed:\n{stderr}"));
    }

    // Find the .wasm file in target/
    let profile = if self.release { "release" } else { "debug" };
    let target_dir = self.crate_dir.join("target").join("wasm32-unknown-unknown").join(profile);

    let wasm_file = if let Some(ref name) = self.target_name {
      target_dir.join(format!("{}.wasm", name.replace('-', "_")))
    } else {
      find_wasm_in_dir(&target_dir)?
    };

    if !wasm_file.exists() {
      return Err(format!("WASM file not found at {}", wasm_file.display()));
    }

    // Step 2: wasm-bindgen
    std::fs::create_dir_all(&self.out_dir)
      .map_err(|e| format!("create out_dir: {e}"))?;

    let mut bindgen = tokio::process::Command::new("wasm-bindgen");
    bindgen
      .arg("--out-dir").arg(&self.out_dir)
      .arg("--target").arg("web")
      .arg("--no-typescript")
      .arg(&wasm_file);
    bindgen.stdout(Stdio::piped()).stderr(Stdio::piped());

    let output = bindgen.output().await.map_err(|e| format!("wasm-bindgen: {e}"))?;
    if !output.status.success() {
      let stderr = String::from_utf8_lossy(&output.stderr);
      return Err(format!("wasm-bindgen failed:\n{stderr}"));
    }

    // Step 3: Write the HTML wrapper
    let js_name = if let Some(ref name) = self.target_name {
      format!("{}.js", name.replace('-', "_"))
    } else {
      find_js_entry(&self.out_dir)?
    };

    let html = super::server::wasm_html_wrapper(&js_name);
    std::fs::write(self.out_dir.join("index.html"), html)
      .map_err(|e| format!("write index.html: {e}"))?;

    Ok(self.out_dir.clone())
  }
}

/// Find the first .wasm file in a directory.
fn find_wasm_in_dir(dir: &Path) -> Result<PathBuf, String> {
  let entries = std::fs::read_dir(dir).map_err(|e| format!("read dir {}: {e}", dir.display()))?;
  for entry in entries.flatten() {
    let path = entry.path();
    if path.extension().is_some_and(|ext| ext == "wasm") {
      return Ok(path);
    }
  }
  Err(format!("no .wasm file found in {}", dir.display()))
}

/// Find the JS entry file generated by wasm-bindgen.
fn find_js_entry(dir: &Path) -> Result<String, String> {
  let entries = std::fs::read_dir(dir).map_err(|e| format!("read dir {}: {e}", dir.display()))?;
  for entry in entries.flatten() {
    let name = entry.file_name().to_string_lossy().to_string();
    if name.ends_with(".js") && !name.ends_with("_bg.js") {
      return Ok(name);
    }
  }
  Err(format!("no JS entry file found in {}", dir.display()))
}

/// High-level: build a component, start a server, return the URL.
///
/// ```ignore
/// let (url, server) = mount_wasm_component("./my-counter-crate", None).await?;
/// page.goto(&url, None).await?;
/// page.wait_for_selector("[data-mounted]", None).await?;
/// // interact with the component...
/// server.stop().await;
/// ```
pub async fn mount_wasm_component(
  crate_dir: &str,
  target_name: Option<&str>,
) -> Result<(String, super::server::ComponentServer), String> {
  let out_dir = std::env::temp_dir()
    .join(format!("ferri_ct_wasm_{}", std::process::id()))
    .join(crate_dir.replace(['/', '\\', '.'], "_"));

  let mut builder = WasmBuilder::new(crate_dir, &out_dir);
  if let Some(name) = target_name {
    builder = builder.target(name);
  }

  let built_dir = builder.build().await?;
  let server = super::server::ComponentServer::start(&built_dir).await?;
  let url = server.url();

  Ok((url, server))
}
