#!/usr/bin/env bash
# A/B Chromium flag sets on the machine that will actually run them.
#
# Exists because the flags worth arguing about are the ones whose value
# depends on the host. Freeing memory per browser buys wall clock only when
# memory is the binding constraint, so a 36GB laptop and a 2-vCPU CI runner
# can disagree completely -- and --disable-dev-shm-usage is declared inside
# Chromium's IS_LINUX block, so on macOS it is a no-op and cannot be
# measured at all. Run this where you deploy.
#
# Reports wall clock (median of RUNS), peak resident memory across the
# browser tree, and peak browser process count, per flag set.
#
# Usage: bench-chrome-flags.sh <spec-dir> [runs] [workers]
#   e.g. bench-chrome-flags.sh target/bench-src/dom 5 4
#
# Generate the spec dirs first with scripts/bench-workloads.sh.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SPEC_DIR="$(cd "${1:?usage: bench-chrome-flags.sh <spec-dir> [runs] [workers]}" && pwd)"
RUNS="${2:-5}"
WORKERS="${3:-4}"
FD_BIN="${FERRIDRIVER_BIN:-$REPO_ROOT/target/release-fast/ferridriver}"
WORK="$REPO_ROOT/target/bench-flags"
[ -x "$FD_BIN" ] || { echo "no ferridriver at $FD_BIN (cargo build --profile release-fast --bin ferridriver)" >&2; exit 2; }

CHROMIUM="${PW_CHROMIUM:-$(ls -d "$HOME"/Library/Caches/ms-playwright/chromium_headless_shell-*/chrome-headless-shell-*/chrome-headless-shell 2>/dev/null | sort | tail -1 || true)}"
[ -n "$CHROMIUM" ] || CHROMIUM="$(ls -d "$HOME"/.cache/ms-playwright/chromium_headless_shell-*/chrome-headless-shell-*/chrome-headless-shell 2>/dev/null | sort | tail -1 || true)"
[ -x "$CHROMIUM" ] || { echo "no chrome-headless-shell found; npx playwright install chromium-headless-shell" >&2; exit 2; }

# name -> extra args. "baseline" is Playwright's switch set, which is what
# ferridriver already ships; every other row adds to it.
#
# NOT covered here: --disable-dev-shm-usage. It is a boolean switch with no
# "un-set" form, so it cannot be A/B'd through args -- testing it means
# deleting it from CHROMIUM_SWITCHES (crates/ferridriver/src/state.rs) and
# rebuilding. It matters on Linux (where /dev/shm is small in containers)
# and is potentially the biggest lever there, so it is worth the rebuild.
SETS=(
  "baseline|"
  "in-process|--in-process-gpu --enable-features=NetworkServiceInProcess2"
)

mkdir -p "$WORK"
ms() { python3 -c 'import time;print(int(time.time()*1000))'; }

peak_browser_rss_mb() {
  local pid="$1" best=0
  while kill -0 "$pid" 2>/dev/null; do
    local rss
    rss=$(ps -eo rss=,comm= 2>/dev/null | grep -iE 'chrome|chromium|headless_shell' | awk '{s+=$1} END {print s+0}')
    rss=${rss:-0}
    [ "$rss" -gt "$best" ] && best=$rss
    sleep 0.4
  done
  echo $((best / 1024))
}

peak_browser_procs() {
  ps -eo comm= 2>/dev/null | grep -ciE 'chrome|chromium|headless_shell' || echo 0
}

echo "workload   $(basename "$SPEC_DIR")"
echo "chromium   $CHROMIUM"
echo "workers    $WORKERS   runs $RUNS"
echo "platform   $(uname -sr)   cores $(getconf _NPROCESSORS_ONLN 2>/dev/null || echo '?')"
if [ -d /dev/shm ]; then
  echo "/dev/shm   $(df -h /dev/shm 2>/dev/null | awk 'NR==2 {print $2" total, "$4" free"}')"
else
  echo "/dev/shm   absent (not Linux; --disable-dev-shm-usage is a no-op here)"
fi
echo

for entry in "${SETS[@]}"; do
  name="${entry%%|*}"
  extra="${entry#*|}"

  args_toml="[]"
  if [ -n "${extra// /}" ]; then
    args_toml="[$(for a in $extra; do printf '"%s", ' "$a"; done | sed 's/, $//')]"
  fi

  cfg="$WORK/$name.toml"
  cat >"$cfg" <<EOF
# GENERATED by scripts/bench-chrome-flags.sh
[test]
testDir = "$SPEC_DIR"
testMatch = ["**/*.spec.ts", "**/*.spec.js", "**/*.test.ts"]
testIgnore = ["**/node_modules/**"]
timeout = 30000
workers = $WORKERS
retries = 0
fullyParallel = true
outputDir = "$WORK/out-$name"
reporter = [{ name = "null" }]

[test.moduleAliases]
"@playwright/test" = "@ferridriver/test"
"playwright" = "ferridriver"

[test.browser]
browser = "chromium"
backend = "cdp-pipe"
headless = true
executablePath = "$CHROMIUM"
args = $args_toml
EOF
  "$FD_BIN" test -c "$cfg" >/dev/null 2>&1 || { echo "$name: SUITE FAILED -- not comparable" >&2; continue; }

  times=()
  peak_rss=0
  peak_procs=0
  for _ in $(seq 1 "$RUNS"); do
    t0=$(ms)
    "$FD_BIN" test -c "$cfg" >/dev/null 2>&1 &
    run_pid=$!
    procs=$(peak_browser_procs)
    rss=$(peak_browser_rss_mb "$run_pid")
    wait "$run_pid" || { echo "$name: SUITE FAILED -- not comparable" >&2; continue 2; }
    t1=$(ms)
    times+=($((t1 - t0)))
    [ "$rss" -gt "$peak_rss" ] && peak_rss=$rss
    [ "$procs" -gt "$peak_procs" ] && peak_procs=$procs
  done

  median=$(printf '%s\n' "${times[@]}" | sort -n | awk '{a[NR]=$1} END {print a[int((NR+1)/2)]}')
  printf '%-16s median %6sms   peak_rss %5sMB   peak_procs %3s   raw %s\n' \
    "$name" "$median" "$peak_rss" "$peak_procs" "${times[*]}"
done

echo
echo "A row only beats baseline if the difference exceeds run-to-run spread"
echo "(compare against the raw samples, not the median alone)."
