#!/usr/bin/env bash
# Suite-level A/B against Playwright Test: the SAME spec files, run by
# both runners, on the SAME Chromium binary, with the same worker count
# and the same parallelism mode.
#
# BENCHMARKING.md is the contract this obeys. In particular: both sides
# are configured here, never by a spec's own playwright.config.ts, so a
# confound like `fullyParallel` (Playwright parallelises by FILE without
# it; ferridriver parallelises by test) cannot silently decide the
# result. Runs are interleaved and a non-zero exit on either side aborts,
# so a suite that quietly stopped running cannot look fast.
#
# Usage: bench-vs-playwright.sh <spec-dir> [runs] [workers]
#
# The spec dir is any directory of Playwright-authored specs; both
# runners get it verbatim. Generated configs land in target/bench/.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SPEC_DIR="$(cd "${1:?usage: bench-vs-playwright.sh <spec-dir> [runs] [workers]}" && pwd)"
RUNS="${2:-5}"
WORKERS="${3:-4}"
# A bare `tests/` leaf says nothing; name the run after its parent.
NAME="$(basename "$SPEC_DIR")"
if [ "$NAME" = tests ] || [ "$NAME" = e2e ]; then
  NAME="$(basename "$(dirname "$SPEC_DIR")")-$NAME"
fi
WORK="$REPO_ROOT/target/bench/$NAME"
FD_BIN="${FERRIDRIVER_BIN:-$REPO_ROOT/target/release-fast/ferridriver}"

# Same browser for both. Playwright's own headless shell is the only
# binary both runners can be pointed at without one of them downloading
# a second copy; PW_CHROMIUM overrides it.
CHROMIUM="${PW_CHROMIUM:-$(ls -d "$HOME"/Library/Caches/ms-playwright/chromium_headless_shell-*/chrome-headless-shell-*/chrome-headless-shell 2>/dev/null | sort | tail -1 || true)}"
[ -n "$CHROMIUM" ] || CHROMIUM="$(ls -d "$HOME"/.cache/ms-playwright/chromium_headless_shell-*/chrome-headless-shell-*/chrome-headless-shell 2>/dev/null | sort | tail -1 || true)"
[ -x "$CHROMIUM" ] || { echo "no chrome-headless-shell found; run: npx playwright install chromium-headless-shell" >&2; exit 2; }
[ -x "$FD_BIN" ] || { echo "no ferridriver at $FD_BIN (cargo build --profile release-fast --bin ferridriver)" >&2; exit 2; }

mkdir -p "$WORK/pw"
rm -rf "$WORK/pw/tests"
cp -R "$SPEC_DIR" "$WORK/pw/tests"

cat >"$WORK/pw/playwright.config.ts" <<EOF
// GENERATED by scripts/bench-vs-playwright.sh — both runners are
// configured identically here so neither side's defaults skew the run.
import { defineConfig } from '@playwright/test';
export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  timeout: 30_000,
  expect: { timeout: 5_000 },
  workers: $WORKERS,
  retries: 0,
  reporter: 'line',
  use: { trace: 'off', video: 'off', screenshot: 'off' },
  projects: [{
    name: 'chromium',
    use: { browserName: 'chromium', headless: true, launchOptions: { executablePath: '$CHROMIUM' } },
  }],
});
EOF

cat >"$WORK/ferridriver.toml" <<EOF
# GENERATED by scripts/bench-vs-playwright.sh
[test]
testDir = "$WORK/pw/tests"
testMatch = ["**/*.spec.ts", "**/*.spec.js", "**/*.test.ts"]
# The bench workspace lives under target/, which the default testIgnore
# excludes — without this, discovery finds nothing.
testIgnore = ["**/node_modules/**"]
timeout = 30000
expectTimeout = 5000
workers = $WORKERS
retries = 0
fullyParallel = true
outputDir = "$WORK/fd-out"
reporter = [{ name = "null" }]

[test.moduleAliases]
"@playwright/test" = "@ferridriver/test"
"playwright" = "ferridriver"

[test.browser]
browser = "chromium"
backend = "cdp-pipe"
headless = true
executablePath = "$CHROMIUM"
EOF

# Its own package.json, or npm walks up and installs into the repo's
# workspace root instead (leaving node_modules here missing entirely).
[ -f "$WORK/pw/package.json" ] || printf '{"name":"fd-bench-%s","private":true,"version":"0.0.0"}\n' "$NAME" >"$WORK/pw/package.json"
if [ ! -d "$WORK/pw/node_modules/@playwright/test" ]; then
  echo "==> installing @playwright/test into $WORK/pw"
  (cd "$WORK/pw" && npm i @playwright/test --silent) || { echo "npm install failed" >&2; exit 2; }
fi

echo "workload   $NAME ($(find "$WORK/pw/tests" -name '*.spec.*' -o -name '*.test.*' | wc -l | tr -d ' ') spec files)"
echo "chromium   $CHROMIUM"
echo "workers    $WORKERS (fullyParallel on both)"
echo "ferridriver $("$FD_BIN" --version)"
echo "playwright  $(cd "$WORK/pw" && npx playwright --version)"
echo

ms() { python3 -c 'import time;print(int(time.time()*1000))'; }

# One discarded warmup per side: bytecode cache, npm resolution, DNS.
"$FD_BIN" test -c "$WORK/ferridriver.toml" >/dev/null 2>&1 || { echo "ferridriver warmup failed" >&2; exit 1; }
(cd "$WORK/pw" && npx playwright test >/dev/null 2>&1) || { echo "playwright warmup failed" >&2; exit 1; }

fd_times=(); pw_times=()
for _ in $(seq 1 "$RUNS"); do
  t0=$(ms); "$FD_BIN" test -c "$WORK/ferridriver.toml" >/dev/null 2>&1 || { echo "ferridriver run failed" >&2; exit 1; }; t1=$(ms)
  fd_times+=($((t1 - t0)))
  t0=$(ms); (cd "$WORK/pw" && npx playwright test >/dev/null 2>&1) || { echo "playwright run failed" >&2; exit 1; }; t1=$(ms)
  pw_times+=($((t1 - t0)))
done

python3 - "${fd_times[*]}" "${pw_times[*]}" <<'PY'
import statistics, sys
fd = [int(x) for x in sys.argv[1].split()]
pw = [int(x) for x in sys.argv[2].split()]
def row(name, xs):
    return f"  {name:<12} median {statistics.median(xs):>7.0f}ms   mean {statistics.mean(xs):>7.0f}ms   min {min(xs):>6}ms   max {max(xs):>6}ms   n={len(xs)}"
print(row("ferridriver", fd))
print(row("playwright", pw))
print(f"  ratio        median {statistics.median(pw)/statistics.median(fd):.2f}x   mean {statistics.mean(pw)/statistics.mean(fd):.2f}x")
print(f"  raw ferridriver {fd}")
print(f"  raw playwright  {pw}")
PY
