#!/usr/bin/env bash
# Run upstream Playwright example suites, UNMODIFIED, against ferridriver.
#
# This is a bug-finding instrument, not a product feature: every failure is
# a ferridriver compat bug until it is recorded in docs/playwright-compat.md
# as an intentional divergence.
#
# The corpus is Playwright's own examples/ tree. It is never edited — the
# checksum manifest (tests/compat/corpus.sha256) is the proof, and the
# per-example ferridriver configs are generated OUTSIDE the corpus.
#
# Every run passes --no-inherit. The layered loader reads the machine, user
# and repo layers before -c, so without it the repo's own testMatch
# (`tests/**`) lands on top of the generated one and the corpus discovers
# zero tests — the harness would be measuring the machine it runs on.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CORPUS="${PLAYWRIGHT_REPO:-/tmp/playwright}"
COMPAT_DIR="$REPO_ROOT/tests/compat"
MANIFEST="$COMPAT_DIR/corpus.sha256"
BASELINE="$COMPAT_DIR/baseline.json"
WORK="$REPO_ROOT/target/compat"
BIN="${FERRIDRIVER_BIN:-$REPO_ROOT/target/debug/ferridriver}"
BACKEND="${COMPAT_BACKEND:-cdp-pipe}"
# Two of the five examples drive demo.playwright.dev; set COMPAT_NETWORK=0 to
# run only the hermetic ones. The skip is always reported, never silent.
NETWORK="${COMPAT_NETWORK:-1}"

UPDATE_MANIFEST=0
UPDATE_BASELINE=0
ONLY=""
while [ $# -gt 0 ]; do
  case "$1" in
    --update-manifest) UPDATE_MANIFEST=1 ;;
    --update-baseline) UPDATE_BASELINE=1 ;;
    --example) ONLY="$2"; shift ;;
    --offline) NETWORK=0 ;;
    -h|--help)
      sed -n '2,12p' "${BASH_SOURCE[0]}"
      echo
      echo "usage: playwright-compat.sh [--example NAME] [--offline]"
      echo "                            [--update-manifest] [--update-baseline]"
      exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
  shift
done

# name|relative test dir|mode|extra config lines (\n-separated)
#   mode=run     execute the suite and compare against the baseline
#   mode=collect discover + bundle only (the suite mutates real remote state)
EXAMPLES=(
  "todomvc|examples/todomvc/tests|run|network"
  "svgomg|examples/svgomg/tests|run|network"
  "mock-battery|examples/mock-battery/tests|run|static:examples/mock-battery/demo-battery-api"
  "mock-filesystem|examples/mock-filesystem/tests|run|static:examples/mock-filesystem/src"
  "github-api|examples/github-api/tests|collect|network"
)

# ── corpus ──────────────────────────────────────────────────────────────────

if [ ! -d "$CORPUS" ]; then
  echo "==> cloning microsoft/playwright into $CORPUS"
  git clone --depth 1 https://github.com/microsoft/playwright "$CORPUS"
fi

corpus_files() {
  for entry in "${EXAMPLES[@]}"; do
    IFS='|' read -r _name dir _mode _opt <<<"$entry"
    [ -d "$CORPUS/$dir" ] || continue
    find "$CORPUS/$dir" -type f \( -name '*.ts' -o -name '*.js' \) -print
  done | sed "s#^$CORPUS/##" | LC_ALL=C sort
}

hash_corpus() {
  # `shasum -a 256` is present on macOS and on every Linux with perl; the
  # coreutils name differs, so probe for it.
  local hasher
  if command -v sha256sum >/dev/null 2>&1; then hasher=sha256sum; else hasher="shasum -a 256"; fi
  (cd "$CORPUS" && corpus_files | tr '\n' '\0' | xargs -0 $hasher)
}

if [ "$UPDATE_MANIFEST" = 1 ]; then
  mkdir -p "$COMPAT_DIR"
  hash_corpus >"$MANIFEST"
  echo "==> wrote $(wc -l <"$MANIFEST" | tr -d ' ') checksums to ${MANIFEST#"$REPO_ROOT"/}"
  exit 0
fi

if [ ! -f "$MANIFEST" ]; then
  echo "no checksum manifest; run: $0 --update-manifest" >&2
  exit 2
fi

echo "==> verifying corpus is byte-for-byte unmodified"
if ! diff -u "$MANIFEST" <(hash_corpus) >"$WORK.manifest.diff" 2>/dev/null; then
  mkdir -p "$WORK"
  diff -u "$MANIFEST" <(hash_corpus) || true
  echo >&2
  echo "corpus differs from the recorded manifest. The corpus must stay UNMODIFIED:" >&2
  echo "  - if you edited a spec, revert it (git -C $CORPUS checkout -- examples/)" >&2
  echo "  - if upstream moved, re-record with: $0 --update-manifest" >&2
  exit 1
fi
rm -f "$WORK.manifest.diff"
echo "    $(wc -l <"$MANIFEST" | tr -d ' ') files match"

[ -x "$BIN" ] || { echo "ferridriver binary not found at $BIN (cargo build --bin ferridriver)" >&2; exit 2; }

# ── per-example config generation + run ─────────────────────────────────────

mkdir -p "$WORK"
: >"$WORK/results.ndjson"
SKIPPED=()

gen_config() {
  local name="$1" dir="$2" mode="$3" opt="$4" port="$5"
  local cfg="$WORK/$name.toml"
  {
    echo "# GENERATED by scripts/playwright-compat.sh — do not edit."
    echo "# The upstream corpus is never touched; only this config is ours."
    echo "[test]"
    echo "testDir = \"$CORPUS/$dir\""
    echo 'testMatch = ["**/*.spec.ts", "**/*.spec.js"]'
    echo "timeout = 30000"
    echo "expectTimeout = 5000"
    echo "workers = 4"
    # One retry, like Playwright's own example configs use on CI. The
    # mock-battery demo app loads `src/index.js` with `async`, so its
    # `getBattery()` microtask races `styles.css`; when the script wins,
    # the app throws on `document.styleSheets[0].insertRule` and renders
    # nothing. That is the app's race, not the driver's — but it is real,
    # and a genuine regression still fails both attempts.
    echo "retries = 1"
    echo "outputDir = \"$WORK/$name-out\""
    echo 'reporter = [{ name = "list" }, { name = "json" }]'
    echo
    echo "# The whole point of the harness: upstream specs keep their own"
    echo "# framework import and link against ferridriver's native module."
    echo "[test.moduleAliases]"
    echo '"@playwright/test" = "@ferridriver/test"'
    echo '"playwright" = "ferridriver"'
    echo
    echo "[test.browser]"
    echo 'browser = "chromium"'
    echo "backend = \"$BACKEND\""
    echo "headless = true"
    case "$opt" in
      static:*)
        echo
        echo "[[test.webServer]]"
        echo "staticDir = \"$CORPUS/${opt#static:}\""
        echo "port = $port"
        ;;
    esac
  } >"$cfg"
  echo "$cfg"
}

port=47900
for entry in "${EXAMPLES[@]}"; do
  IFS='|' read -r name dir mode opt <<<"$entry"
  port=$((port + 1))

  if [ -n "$ONLY" ] && [ "$ONLY" != "$name" ]; then continue; fi
  if [ ! -d "$CORPUS/$dir" ]; then
    SKIPPED+=("$name: not present in the corpus ($dir)")
    continue
  fi
  if [ "$opt" = network ] && [ "$NETWORK" != 1 ]; then
    SKIPPED+=("$name: needs network (demo.playwright.dev / api.github.com), COMPAT_NETWORK=0")
    continue
  fi

  cfg="$(gen_config "$name" "$dir" "$mode" "$opt" "$port")"
  echo
  echo "==> $name ($mode, $BACKEND)"
  if [ "$mode" = collect ]; then
    # The suite mutates real remote state (creates/deletes a GitHub repo), so
    # the gate exercises discovery + bundling + registration only.
    if out="$("$BIN" --no-inherit test -c "$cfg" --list 2>&1)"; then
      n="$(printf '%s\n' "$out" | sed -n 's/^ *\([0-9][0-9]*\) test(s) found$/\1/p' | tail -1)"
      n="${n:-0}"
      echo "$out"
      jq -nc --arg e "$name" --arg n "$n" \
        '{example:$e, mode:"collect", collected:($n|tonumber)}' >>"$WORK/results.ndjson"
    else
      echo "$out"
      jq -nc --arg e "$name" '{example:$e, mode:"collect", error:true}' >>"$WORK/results.ndjson"
    fi
    continue
  fi

  "$BIN" --no-inherit test -c "$cfg" || true
  report="$WORK/$name-out/results.json"
  if [ ! -f "$report" ]; then
    echo "no JSON report at $report" >&2
    jq -nc --arg e "$name" '{example:$e, mode:"run", error:true}' >>"$WORK/results.ndjson"
    continue
  fi
  # `retries = 1` means a retried test appears twice; only its final
  # attempt is the outcome.
  jq -c --arg e "$name" '
    [ .. | objects | select(has("specs")) | .specs[]
      | . as $spec
      | .tests[].results[]
      | {example:$e, mode:"run",
         id: (($spec.file | sub(".*/examples/";"examples/")) + " > " + $spec.title),
         attempt: (.retry // 0),
         status: .status,
         error: (.errors[0].message // null)} ]
    | group_by(.id) | map(max_by(.attempt))[]' "$report" >>"$WORK/results.ndjson"
done

# ── baseline comparison ─────────────────────────────────────────────────────

jq -s 'map(select(.mode == "run" and has("id"))) | map({key: .id, value: .status}) | from_entries' \
  "$WORK/results.ndjson" >"$WORK/current.json"

if [ "$UPDATE_BASELINE" = 1 ]; then
  mkdir -p "$COMPAT_DIR"
  cp "$WORK/current.json" "$BASELINE"
  echo
  echo "==> baseline updated: ${BASELINE#"$REPO_ROOT"/}"
fi

echo
echo "──────────────────────────────────────────────────────────────"
jq -r '
  group_by(.example)[] |
  (.[0].example) as $e |
  if .[0].mode == "collect" then
    "\($e): collected \(.[0].collected // 0) (not executed — mutates remote state)"
  elif (.[0] | has("id") | not) then
    "\($e): SUITE DID NOT RUN (the whole bundle failed to load)"
  else
    ( [.[] | select(.status == "passed")] | length ) as $p |
    ( length ) as $t |
    "\($e): \($p)/\($t) passed"
  end' -s "$WORK/results.ndjson"

total="$(jq -s '[.[] | select(.mode == "run" and has("id"))] | length' "$WORK/results.ndjson")"
passed="$(jq -s '[.[] | select(.mode == "run" and .status == "passed")] | length' "$WORK/results.ndjson")"
echo "──────────────────────────────────────────────────────────────"
echo "TOTAL: $passed/$total passed"

for s in ${SKIPPED+"${SKIPPED[@]}"}; do echo "SKIPPED $s"; done

status=0
if [ -f "$BASELINE" ] && [ "$UPDATE_BASELINE" != 1 ]; then
  regressions="$(jq -r --slurpfile b "$BASELINE" '
    . as $cur | $b[0] | to_entries
    | map(select(.value == "passed" and ($cur[.key] // "missing") != "passed"))
    | .[] | "  REGRESSED \(.key) -> \($cur[.key] // "missing")"' "$WORK/current.json")"
  improvements="$(jq -r --slurpfile b "$BASELINE" '
    . as $cur | $cur | to_entries
    | map(select(.value == "passed" and ($b[0][.key] // "missing") != "passed"))
    | .[] | "  NOW PASSING \(.key)"' "$WORK/current.json")"
  if [ -n "$improvements" ]; then echo; echo "$improvements"; fi
  if [ -n "$regressions" ]; then
    echo
    echo "$regressions"
    echo
    echo "baseline: ${BASELINE#"$REPO_ROOT"/} (re-record with --update-baseline)"
    status=1
  fi
fi

echo
echo "failures by class:"
jq -rs '[.[] | select(.mode == "run" and has("id") and .status != "passed")]
        | group_by(.error // "unknown")
        | sort_by(-length)[]
        | "  \(length)x  \(.[0].error // "unknown" | split("\n")[0])"' "$WORK/results.ndjson"

exit $status
